<!-- R Commander Markdown Template -->

Replace with Main Title
=======================

### Your Name

### `r as.character(Sys.Date())`

```{r echo=FALSE}
# include this code chunk as-is to set options
knitr::opts_chunk$set(comment=NA, prompt=TRUE, out.width=750, fig.height=8, fig.width=8)
library(Rcmdr)
library(car)
library(RcmdrMisc)
```


```{r echo=FALSE}
# include this code chunk as-is to enable 3D graphs
library(rgl)
knitr::knit_hooks$set(webgl = hook_webgl)
```


```{r}
load("C:/Users/ivanm/Desktop/Uni/Estadistica/Practica/.RData")
```

```{r}
setwd("C:/Users/ivanm/OneDrive/Documents")
```


```{r}
Dades <- read.csv2("Dades.csv", header = T)
```


```{r}
Dades
```


```{r}
summary(Dades)
```

```{r}
dades1 <- c(0.15,0.17,0.13,0.18,0.15,0.16,0.17,0.15,0.17,0.15,0.19,0.18,0.17,0.15,0.13)
```


```{r}
dades2 <- rnorm(15, 0.16, 0.01772811)
```


```{r}
dades3 <- rnorm(15, 0.18, 0.01772811)
```


```{r}
t.test(dades1, dades2, alternative="two.sided", conf.level = 0.99, paired = TRUE)
```


```{r}
t.test(dades1, dades2, conf.level = 0.95)
```


```{r}
t.test(dades1, dades3, conf.level = 0.95)
```


```{r}
t.test(dades3, dades2, conf.level = 0.95)
```

```{r}
Dades <- read.csv2("Dades.csv", header = T)
```


```{r}
Dades
```


```{r}
summary(Dades)
```

```{r}
dades1 <- c(0.15,0.17,0.13,0.18,0.15,0.16,0.17,0.15,0.17,0.15,0.19,0.18,0.17,0.15,0.13)
```


```{r}
dades2 <- rnorm(15, 0.16, 0.01772811)
```


```{r}
dades3 <- rnorm(15, 0.18, 0.01772811)
```


```{r}
t.test(dades1, dades2, alternative="two.sided", conf.level = 0.99, paired = TRUE)
```


```{r}
t.test(dades1, dades2, conf.level = 0.95)
```


```{r}
t.test(dades1, dades3, conf.level = 0.95)
```


```{r}
t.test(dades3, dades2, conf.level = 0.95)
```


```{r}
editDataset(Dades)
```

```{r}
summary(Dades)
```


```{r}
Dades <- read.csv2("Dades.csv", header = T)
```


```{r}
Dades
```

```{r}
summary(Dades)
```


```{r}
numSummary(Dades[,"Dades", drop=FALSE], statistics=c("mean", "sd", "IQR", "quantiles"),
quantiles=c(0,.25,.5,.75,1))
```


```{r}
normalityTest(~Dades, test="lillie.test", data=Dades)
```


```{r}
with(Dades, (t.test(Dades, alternative='two.sided', mu=0.0, conf.level=.99)))
```


```{r}
dades1 <- c(0.15,0.17,0.13,0.18,0.15,0.16,0.17,0.15,0.17,0.15,0.19,0.18,0.17,0.15,0.13)
```


```{r}
dades2 <- rnorm(15, 0.16, 0.01772811)
```


```{r}
dades3 <- rnorm(15, 0.18, 0.01772811)
```


```{r}
t.test(dades1, dades2, alternative="two.sided", conf.level = 0.99, paired = TRUE)
```


```{r}
t.test(dades1, dades2, conf.level = 0.95)
```


```{r}
t.test(dades1, dades3, conf.level = 0.95)
```


```{r}
t.test(dades3, dades2, conf.level = 0.95)
```

```{r}
Dades <- read.csv2("Dades.csv", header = T)
```


```{r}
Dades
```

```{r}
summary(Dades)
```


```{r}
numSummary(Dades[,"Dades", drop=FALSE], statistics=c("mean", "sd", "IQR", "quantiles"),
quantiles=c(0,.25,.5,.75,1))
```


```{r}
normalityTest(~Dades, test="lillie.test", data=Dades)
```


```{r}
with(Dades, (t.test(Dades, alternative='two.sided', mu=0.0, conf.level=.99)))
```


```{r}
dades1 <- c(0.15,0.17,0.13,0.18,0.15,0.16,0.17,0.15,0.17,0.15,0.19,0.18,0.17,0.15,0.13)
```


```{r}
dades2 <- rnorm(15, 0.16, 0.01772811)
```


```{r}
dades3 <- rnorm(15, 0.18, 0.01772811)
```


```{r}
t.test(dades1, dades2, alternative="two.sided", conf.level = 0.99, paired = TRUE)
```


```{r}
t.test(dades1, dades2, conf.level = 0.95)
```


```{r}
t.test(dades1, dades3, conf.level = 0.95)
```


```{r}
t.test(dades3, dades2, conf.level = 0.95)
```


